### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by w4ll3** [pypa/packaging-problems#493] opened 2021-04-13 00:04 UTC
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

macOS bigSur 11.2.3

2. What is your Python version?

Python 3.8

3. What version of pip do you have?

Pip 21.0.1

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

https://packaging.python.org/tutorials/packaging-projects/#generating-distribution-archives

5. Could you describe your issue in as much detail as possible?

When I run `python3 -m build` this is what I got.

```
MacBookPro:python adrian$ ls -la
total 56
drwxr-xr-x   8 adrian  staff    256 Apr 12 13:46 .
drwxr-xr-x  18 adrian  staff    576 Apr 12 17:15 ..
-rw-r--r--   1 adrian  staff     18 Apr 12 13:46 .gitignore
-rw-r--r--   1 adrian  staff  11357 Apr 12 13:46 LICENSE
-rw-r--r--   1 adrian  staff   1768 Apr 12 13:46 README.md
drwxr-xr-x   8 adrian  staff    256 Apr 12 13:46 didkit
-rw-r--r--   1 adrian  staff    104 Apr 12 13:46 pyproject.toml
-rw-r--r--   1 adrian  staff    615 Apr 12 13:46 setup.cfg
MacBookPro:python adrian$ python3 -m build
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Library/Python/3.8/site-packages/build/__main__.py", line 214, in <module>
    main(sys.argv[1:], 'python -m build')
  File "/Library/Python/3.8/site-packages/build/__main__.py", line 206, in main
    build_package(args.srcdir, outdir, distributions, config_settings, not args.no_isolation, args.skip_dependencies)
  File "/Library/Python/3.8/site-packages/build/__main__.py", line 94, in build_package
    _build_in_isolated_env(builder, outdir, distributions, config_settings)
  File "/Library/Python/3.8/site-packages/build/__main__.py", line 52, in _build_in_isolated_env
    with IsolatedEnvBuilder() as env:
  File "/Library/Python/3.8/site-packages/build/env.py", line 91, in __enter__
    executable, scripts_dir = _create_isolated_env_venv(self._path)
  File "/Library/Python/3.8/site-packages/build/env.py", line 199, in _create_isolated_env_venv
    venv.EnvBuilder(with_pip=True).create(path)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/venv/__init__.py", line 68, in create
    self._setup_pip(context)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/venv/__init__.py", line 289, in _setup_pip
    subprocess.check_output(cmd, stderr=subprocess.STDOUT)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/var/folders/yj/05x9wcn88xl2pm008k8xqgmr0000gn/T/build-env-48lditsw/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']' died with <Signals.SIGABRT: 6>.
```

**Comment by layday** [comment] 2021-04-13 00:17
This looks like it might be an issue with the macOS Command Line Tools build of Python.  Could you try with virtualenv by reinstalling build with the `virtualenv` extra:  `python3 -m pip install -U build[virtualenv]`?

**Comment by uranusjr** [comment] 2021-04-13 09:59
I must admit I don’t understand why this is happening at all. Could you try the following?

```
$ /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/bin/python3 -m venv --without-pip /tmp/test-venv  # This creates a /tmp/test-venv directory; remove it after testing!
$ /tmp/test-venv/bin/python -Im ensurepip --upgrade --default-pip  # This should emit some output.
```

**Comment by w4ll3** [comment] 2021-04-13 12:37
@layday that did the trick, I don't really know why. But thanks.

**Comment by sebkraemer** [comment] 2021-04-15 21:52
> python3 -m pip install -U build[virtualenv]

This did the trick for me as well, thanks!

I'm coming from https://github.com/pypa/packaging-problems/issues/488 where I got the same or pretty similar error message. My error report output  also uses a python from Apple's CommandLineTools, while everything else seems to point to a brewed version:

```bash
$  export|grep VIRTUALENVWRAPPER_PYTHON
VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python3

$ which python3
/usr/local/bin/python3

$  ls -l `which python3`                
lrwxr-xr-x  1 sebi  admin  38 Apr  8 08:25 /usr/local/bin/python3 -> ../Cellar/python@3.9/3.9.4/bin/python3
```

**Comment by layday** [comment] 2021-04-16 00:27
I assume it simply wasn't the case that it pointed to the brewed Python 9 days ago when you opened the issue - 3.9.4 was only released yesterday after all :)

**Comment by layday** [comment] 2021-04-17 01:44
I'll close this one now.  Feel free to open a new ticket if you encounter an issue with packaging.

**Closed by layday** 2021-04-17 01:44 UTC

**Comment by sebkraemer** [comment] 2021-04-19 09:45
> I assume it simply wasn't the case that it pointed to the brewed Python 9 days ago when you opened the issue :)

Yeah, you got me there 😆 After Big Sur update (or something else?!) I couldn't reproduce the issue any more since for whatever reason, `virtualenvwrapper.sh` wasn't found.

I made a note of the special `build`  installation step which I believe was still necessary for me.
