### ISSUE TITLE
TLSv1.0/TLSv1.1 rolling brownouts are not transparent

### ISSUE THREAD

**Issue by awallace-cray** [pypa/packaging-problems#130] opened 2018-03-22 22:13 UTC
FYI, The pip clients we're using sure don't pass along any error 403 message. 
The connection "succeeds" but the client just won't find anything it is looking for (pip install). 
No response needed. 
Thanks.

**Comment by awallace-cray** [comment] 2018-03-22 22:14
Looks like 6.0.6. 
It is baked-in.

**Comment by alex** [comment] 2018-03-22 22:15
Baked into what?

Can you try with the latest pip, 9.0.3?

**Comment by awallace-cray** [comment] 2018-03-22 22:19
Baked-in the project config files. Which are probably up for grabs now anyway, because the TLSv1.0/TLSv1.1 change. 
Will let you know about trying pip 9.0.3. 
I think root cause on our side, is using old SLES-11 machines in this project.

**Comment by dstufft** [comment] 2018-03-22 22:20
Ancient versions of OpenSSL will definitely be an issue.

**Comment by alex** [comment] 2018-03-22 22:21
I don't know anything about SLES, but https://www.suse.com/documentation/suse-best-practices/singlehtml/securitymodule/securitymodule.html seems like the relevant doc

**Comment by awallace-cray** [comment] 2018-03-23 12:33
Our local PyPI mirror supports http and is working well.  I did not build this mirror, and do not know how it works. 

Pip install needs parameters `--index-url $mirror_url --trusted-host $mirror_hostname`,
which can be passed to pip in different ways.  All good. 

However, many of our scripts also use easy_install. To go get virtualenv, for example. 
Easy_install works w our mirror if you add `-i $mirror_url` to its command line. 
I wish I had an "easier" way to pass easy_install parameters, like with conf files or an env variables.  Ideally, this should work even with old versions of easy_install.

**Comment by alex** [comment] 2018-03-23 13:11
We _strongly_ recommend you stop using easy_install; it's been deprecated for a long time and hasn't really kept up with improvements to the packaging ecosystem.

**Comment by awallace-cray** [comment] 2018-03-23 13:20
Good advice. 

Do you happen to know when the TLSv1.0/TLSv1.1 policy will be fully enforced on pypi.org?
- Thanks

**Comment by alex** [comment] 2018-03-23 13:22
We'll be gradually ratcheting up the brownout periods over the next few weeks; April 8th is our current target for fully disabling them.

**Comment by awallace-cray** [comment] 2018-03-23 15:13
Said I'd get back to you on the pip error message. 

time: 2018-03-23 08:06 PT
host: an old SLES-11 machine, but I am using a recently-built Python 2.7 (user-built from source)

```
$ pip install argparse # No 403 error message
Collecting argparse
  Could not find a version that satisfies the requirement argparse (from versions: )
No matching distribution found for argparse

$ pip install -v argparse # there it is
Collecting argparse
  1 location(s) to search for versions of argparse:
  * https://pypi.python.org/simple/argparse/
  Getting page https://pypi.python.org/simple/argparse/
  Looking up "https://pypi.python.org/simple/argparse/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): pypi.python.org
  "GET /simple/argparse/ HTTP/1.1" 403 109
  Status code 403 not in [200, 203, 300, 301]
  Could not fetch URL https://pypi.python.org/simple/argparse/: 403 Client Error: Brownout of Legacy TLS for url: https://pypi.python.org/simple/argparse/ - skipping
  Could not find a version that satisfies the requirement argparse (from versions: )
Cleaning up...
No matching distribution found for argparse

$ pip --version
pip 9.0.1 from /var/tmp/chapelu/awallace/venv/lib/python2.7/site-packages (python 2.7)

$ python --version
Python 2.7.13

$ type python
python is hashed (/ptmp/chapelu/awallace/venv/bin/python)
```

**Comment by alex** [comment] 2018-03-23 15:35
@dstufft this seems like an issue, pip should, without `-v`, recognize a non-200 status code and print something useful. Is there an existing pip tracking bug for this?

**Comment by dstufft** [comment] 2018-03-23 15:36
It did print the status code out right?

```
Could not fetch URL https://pypi.python.org/simple/argparse/: 403 Client Error: Brownout of Legacy TLS for url: https://pypi.python.org/simple/argparse/ - skipping
```

**Comment by dstufft** [comment] 2018-03-23 15:36
I don't tihnk there's a bug for tracking any additional changes to that though, no.

**Comment by alex** [comment] 2018-03-23 15:40
It only printed that with `-v` though -- it should do more by default.

**Comment by dstufft** [comment] 2018-03-23 15:41
Oh right. Yea open an issue

**Comment by alex** [comment] 2018-03-23 15:42
https://github.com/pypa/pip/issues/5111

**Comment by jvanasco** [comment] 2018-03-25 22:10
FYI, pip 9.0.1 does not pass on any message or note a 403.  It just says no matching versions are found, for everything.  One must pass in `-vvvv` to see what happened.

**Comment by ntwaddell** [comment] 2018-03-26 22:40
So what needs to be done to fix this?  it's causing some of my python projects to fail in TravisCI

Could not fetch URL https://pypi.python.org/simple/pip/: 403 Client Error: Brownout of Legacy TLS 

Just upgrade OpenSSL?

**Comment by jvanasco** [comment] 2018-03-26 22:43
@ntwaddell try to upgrade pip first.  you can download/run the get-pip.py from here: https://bootstrap.pypa.io/

that should fix several environments.

**Comment by alex** [comment] 2018-03-27 12:10
What platform are you hitting this on with Travis CI? We should make sure any builtin packages they have are updated.

**Comment by ntwaddell** [comment] 2018-03-27 17:26
@alex I'm using TravisCI Enterprise, it always takes them longer to update their enterprise platform.

Build language: python
Build group: stable
Build dist: precise
Description:	Ubuntu 12.04.5 LTS
Release:	12.04

OpenSSL is OpenSSL 1.0.1 14 Mar 2012

**Comment by alex** [comment] 2018-03-27 17:42
@ntwaddell On Ubuntu Precise you should be able to get a working OpenSSL by doing `sudo apt-get update && sudo apt-get install --only-upgrade openssl libssl-dev`.

**Comment by jvanasco** [comment] 2018-03-27 20:15
@ntwaddell FYI, that's the first heartbleed release. That should have been upgraded years ago.

**Comment by gberriz** [comment] 2018-03-31 00:49
Installing an up-to-date pip is no solution, because one gets exactly the same error when one tries that:

```
% python get-pip.py -vvv --no-cache-dir --user
Collecting pip
  1 location(s) to search for versions of pip:
  * https://pypi.python.org/simple/pip/
  Getting page https://pypi.python.org/simple/pip/
  Starting new HTTPS connection (1): pypi.python.org
  https://pypi.python.org:443 "GET /simple/pip/ HTTP/1.1" 403 109
  Could not fetch URL https://pypi.python.org/simple/pip/: 403 Client Error: Brownout of Legacy TLS for url: https://pypi.python.org/simple/pip/ - skipping
  Could not find a version that satisfies the requirement pip (from versions: )
Cleaning up...
No matching distribution found for pip
Exception information:
Traceback (most recent call last):
  File "/tmp/tmpvDyfeC/pip.zip/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/tmp/tmpvDyfeC/pip.zip/pip/commands/install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "/tmp/tmpvDyfeC/pip.zip/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/tmp/tmpvDyfeC/pip.zip/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/tmp/tmpvDyfeC/pip.zip/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/tmp/tmpvDyfeC/pip.zip/pip/index.py", line 514, in find_requirement
    'No matching distribution found for %s' % req
DistributionNotFound: No matching distribution found for pip
```

Is there some other way to reliably avoid this problem?

**Comment by brainwane** [comment] 2018-04-02 18:15
@ntwaddell you should upgrade pip. Official release notes: https://pip.pypa.io/en/stable/news/

@awallace-cray asked:

> Do you happen to know when the TLSv1.0/TLSv1.1 policy will be fully enforced on pypi.org?

The short answer, as Alex mentioned, is April 8th. More details:

As PSF blogged last year https://pyfound.blogspot.com/2017/01/time-to-upgrade-your-python-tls-v12.html , on June 30, 2018, all Python.org sites are going to entirely stop supporting TLS versions 1.0 and 1.1, because our CDN provider is deprecating support for those versions. 

We are launching the new PyPI (in beta at https://pypi.org) this month and replacing the legacy PyPI (https://pypi.python.org). Here's the beta announcement for the new PyPI: https://pyfound.blogspot.com/2018/03/warehouse-all-new-pypi-is-now-in-beta.html Warehouse, the codebase for the new PyPI, does not support TLS 1.0 or 1.1.

So, as of late March, the Python Package Index has started doing rolling brownouts of the deprecated TLS versions. For some portion of each hour, anyone attempting to access PyPI with TLSv1.0 or TLSv1.1 is supposed to get a 403 response with an informative error. As we get closer to the deadline, we will be ramping up the amount of time the endpoint is down for the deprecated TLS versions. The ultimate goal is to have it be 100% unavailable on and after April 8th, prior to the final deadline (because we can give a good error message -- once June 30th hits, it will just be an uninformative OpenSSL error).

More info:

* https://github.com/pypa/warehouse/issues/3293
* https://github.com/pypa/warehouse/issues/3411
* https://status.python.org/incidents/btjtz01lzp88

**Comment by jvanasco** [comment] 2018-04-02 18:26
@brainwane said:
> The ultimate goal is to have it be 100% unavailable on and after April 8th, prior to the final deadline (because we can give a good error message -- once June 30th hits, it will just be an uninformative OpenSSL error).

Have you looked into doing a rolling brownout that triggers OpenSSL errors after April 8th?

The informative 403 response is entirely swallowed by some `pip` versions. An OpenSsl error **might** raise an uncaught exception, and lead people into checkout out the website (where they'd find info on the migration).

**Comment by alex** [comment] 2018-04-02 18:35
I'm not sure we have the technical ability to trigger the OpenSSL error in advance of our CDN -- it requires changing how they perform the TLS handshake.

**Comment by jvanasco** [comment] 2018-04-02 18:45
I totally forgot there's a cdn :(

**Comment by dstufft** [comment] 2018-04-02 19:14
We can trigger tls errrors pretty much whenever we want, but it’s all or nothing and a one way switch. Once we disable it, it’s gone.

**Comment by tueksta** [comment] 2018-04-04 12:02
Brownout by sending 403 for "some portion of each hour" is a horrible decision. We have flickering CI due to this and with the logs not showing the actual error unless you escalate the verbosity levels it leaves everyone wondering why something that has been working perfectly until now sometimes fails and sometimes succeeds.

**Comment by jjshoe** [comment] 2018-04-04 15:16
Fix for osx?

**Comment by alex** [comment] 2018-04-04 15:54
@jjshoe Upgrading to the latest version of pip (9.0.3) should always resolve this issue on macOS. If `pip install -U pip` doesn't work because of the brownout, `curl https://bootstrap.pypa.io/get-pip.py | python -` will.

**Comment by shrielastica** [comment] 2018-04-05 23:48
@alex: Even after pip upgrade, still the issue is seen. Please advise

04-05-2018 16:43:32 INFORMATION - [Execute ID: 12] : Staring execution of command line: /Library/Frameworks/Python.framework/Versions/3.5/bin/pip3 --verbose --trusted-host=pypi.python.org install requests
04-05-2018 16:43:32 INFORMATION - [Execute ID: 12] : **** BEGIN COMMAND OUTPUT ****
04-05-2018 16:43:33 INFORMATION - [Execute ID: 12] : The directory '/Users/automation/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/automation/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting requests
  1 location(s) to search for versions of requests:
  * https://pypi.python.org/simple/requests/
  Getting page https://pypi.python.org/simple/requests/
  Starting new HTTPS connection (1): pypi.python.org
  "GET /simple/requests/ HTTP/1.1" 403 109
  Could not fetch URL https://pypi.python.org/simple/requests/: 403 Client Error: Brownout of Legacy TLS for url: https://pypi.python.org/simple/requests/ - skipping
  Could not find a version that satisfies the requirement requests (from versions: )
Cleaning up...
No matching distribution found for requests
Exception information:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pip/commands/install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pip/index.py", line 514, in find_requirement
    'No matching distribution found for %s' % req
pip.exceptions.DistributionNotFound: No matching distribution found for requests
Starting new HTTPS connection (1): pypi.python.org
"GET /pypi/pip/json HTTP/1.1" 403 109
There was an error checking the latest version of pip
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pip/utils/outdated.py", line 128, in pip_version_check
    resp.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pip/_vendor/requests/models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
pip._vendor.requests.exceptions.HTTPError: 403 Client Error: Brownout of Legacy TLS for url: https://pypi.python.org/pypi/pip/json

**Comment by alex** [comment] 2018-04-05 23:49
@shrielastica what OS version is this?

**Comment by gajjar8055** [comment] 2018-04-09 09:47
I have spent around 5 hours  and almost die, man

**Comment by shawngustaw** [comment] 2018-04-09 17:42
I'm not sure if this is related at all but a coworker was having similar issues and `brew install python@2` ended up fixing it. Oddly, downloading Python 2.7.14 directly from the Python website didn't work, but installing via brew and overwriting seems to be using the correct OpenSSL version.

**Comment by awallace-cray** [comment] 2018-04-09 17:51
I can confirm: `brew install python@2` installs newer version of easy_install and pip in /usr/local/bin, and these clients can connect to PyPI even when the system-installed Python-2 easy_install or pip cannot.  

I've read posts about `brew install python` fixing the same or similar problem for Python 3.

**Comment by brainwane** [comment] 2018-04-13 22:24
[A comment on LWN](https://lwn.net/Articles/751458/) suggests we should have an announcement about this on python.org. Someone could write something to post to http://blog.python.org/ which syndicates to that front page -- caution that only about the first ~30 characters will show up.

**Comment by alex** [comment] 2018-04-13 22:25
At this point we've had TLS 1.0/1.1 disabled 100% of the time for a few days with limited feedback, I'm reluctant to think we need further publication of this.

**Comment by alex** [comment] 2018-04-16 17:37
Can you suggest what communications channels we could have promoted the brownouts on to help you see them?

**Comment by brainwane** [comment] 2019-08-12 18:44
Now that we have entirely stopped supporting TLS 1.0 and 1.1, I am closing this issue. To be notified of future breaking changes to PyPI, please subscribe to [the pypi-announce mailing list](https://mail.python.org/mailman3/lists/pypi-announce.python.org/).

**Closed by brainwane** 2019-08-12 18:44 UTC
Labels: pypi-tls
