### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by Sadanandgowda** [pypa/packaging-problems#379] opened 2020-07-16 20:26 UTC
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

Windows 10

2. What is your Python version?

Python 3.7.1

3. What version of pip do you have?

20.1.1

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

https://packaging.python.org/tutorials/packaging-projects/

5. Could you describe your issue in as much detail as possible?

Now run this command from the same directory where setup.py is located:

python3 setup.py sdist bdist_wheel,

After Execution

This command should output a lot of text and once completed should generate two files in the dist directory:

dist/
  example_pkg_YOUR_USERNAME_HERE-0.0.1-py3-none-any.whl
  example_pkg_YOUR_USERNAME_HERE-0.0.1.tar.gz

No File generated or Output

**Comment by uranusjr** [comment] 2020-07-17 04:12
Use `py` instead. See pypa/packaging.python.org#751.

**Comment by merwok** [comment] 2020-07-17 17:14
The OP didn’t say that they got an error message about command not found, but that there was no output :thinking:

**Comment by pfmoore** [comment] 2020-07-17 18:43
The Windows Store distribution of Python is shipped as a `python.exe` (and a `python3.exe`, apparently) file that comes with the OS. That `python` command launches the Windows Store to let you download Python, and if you do so, `python.exe`/`python3.exe` is replaced with the actual Python executable.

The problem is that if that initial stub is run with any command line arguments, it silently does nothing. And if you install Python from python.org, that version doesn't overwrite the stub.

So what you end up with is a real Python installation that you can run using `py.exe`, plus a `python.exe` and `python3.exe` stubs that silently do nothing if passed any command line arguments. That's the symptom the OP is seeing.

I raised https://bugs.python.org/issue41327 to flag awareness of the issue with CPython. Let's see what happens.

**Comment by pradyunsg** [comment] 2020-08-30 11:07
Closing since there's a b.p.o. bug tracking this issue, and there's no reason to be tracking that issue here.

**Closed by pradyunsg** 2020-08-30 11:07 UTC
