### ISSUE TITLE
HTTPError: 404 Client Error: Not Found for url: https://pypi.org/legacy/

### ISSUE THREAD

**Issue by sithlord1234** [pypa/packaging-problems#156] opened 2018-05-26 17:25 UTC

**Comment by pradyunsg** [comment] 2018-05-26 20:07
@sithlord1234 Why is this a problem?

**Comment by sithlord1234** [comment] 2018-05-31 19:14
I don't know but it did not allow me to upload to pypi

**Comment by pradyunsg** [comment] 2018-06-03 06:12
This is a duplicate of #155.

**Closed** 2018-06-03 07:27 UTC
