### ISSUE TITLE
An alternative to importable eggs for package plugins?

### ISSUE THREAD

**Issue by cas--** [pypa/packaging-problems#212] opened 2018-11-20 16:50 UTC
I was asked by @jaraco in https://github.com/pypa/setuptools/issues/1097#issuecomment-439660425 to describe why our project is still using what are considered deprecated eggs. 

The [Deluge](https://github.com/deluge-torrent/deluge) python project has been using eggs with entry_points for it's plugins for many years now. Eggs have been a simple mechanism for a plugin author to create a distributable pure-python plugin that users drop into to their Deluge config directory which Deluge will find and import. Just to note that expecting end-users to install plugins via pip is not workable as pip may not be available or complicates the steps involved.

A summary of how we use the eggs currently, from [pluginmanagerbase.py](https://github.com/deluge-torrent/deluge/blob/develop/deluge/pluginmanagerbase.py#L95):

```python
pkg_env = pkg_resources.Environment([plugin_dir], None)
# Get a list of importable plugins
available_plugins = [name for name in pkg_env]
# Load a plugin name from available_plugins
egg = pkg_env[plugin_name][0]        
name = list(egg.get_entry_map(group))[0]
egg.load_entry_point(group, name)
# The plugin egg is imported and ready to be started
```

In moving to Python 3 I became aware that eggs are considered deprecated, along with pkg_resources namespace but eggs rely on the latter and I am now facing pkg_resources namespace issues in https://github.com/pypa/setuptools/issues/1097. Also if PyPA support for eggs is dropped in the future it will cause major headaches for the Deluge project and I would like to somewhat future proof the project in the move to Python 3. So I would really like a straightforward solution for replacing eggs.  

It was suggested that wheels with zipimport might be used but this doesn't seem to have the same package discovery as eggs, i.e. entry_points or namespace. In addition I was under the impression that wheels were not meant to be importable.

I am open to suggestions on the best way to solve this :)

**Comment by cas--** [comment] 2018-11-21 13:16
So a bit of searching let me to this [pluggy discussion](https://github.com/pytest-dev/pluggy/issues/183) on replacing pkg_resources with entrypoints, importlib-resources and importlib_metadata.

And an issue for entrypoints to support wheels: https://github.com/takluyver/entrypoints/issues/24

**Comment by cas--** [comment] 2019-04-26 13:37
@jaraco I am having namespace problems with importing my plugins as wheels. Am I missing something?

I cloned https://github.com/pypa/sample-namespace-packages to use as examples.

Native namespace issue:
```
cd native/pkg_a
python3 setup.py bdist_wheel
cd ..
env PYTHONPATH=pkg_a/dist/example_pkg_a-1-py3-none-any.whl python3
>>> import example_pkg.a
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'example_pkg.a'
>>> 
```

Pkgutil works
```
cd pkgutil/pkg_a
python3 setup.py bdist_wheel
cd ..
env PYTHONPATH=pkg_a/dist/example_pkg_a-1-py3-none-any.whl python3
>>> import example_pkg.a
>>>
```
But it doesn't handle an already declared namespace
```
cd pkgutil
mkdir example_pkg
cp pkg_a/example_pkg/__init__.py example_pkg
env PYTHONPATH=pkg_a/dist/example_pkg_a-1-py3-none-any.whl python3
>>> import example_pkg.a
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'example_pkg.a'
>>> 
```

With pkg_resources and egg it works as expected:
```
cd pkg_resources
mkdir example_pkg
cp pkg_a/example_pkg/__init__.py example_pkg
cd pkg_a
python3 setup.py bdist_egg
cd ..
env PYTHONPATH=pkg_a/dist/example_pkg_a-1-py3.7.egg python3
>>> import example_pkg.a
>>>
```

Above examples all using Python 3.7

**Comment by jaraco** [comment] 2019-04-26 17:33
My initial instinct is you've stumbled on a bug in Python w.r.t. PEP 420 namespace packages in zip files. But, trying to create a simple replication of that proves false:

```
draft $ mkdir -p example_pkg/a                                                                                                                                                 
draft $ touch example_pkg/a/__init__.py                                                                                                                                        
draft $ zip -r example_pkg example_pkg                                                                                                                                         
  adding: example_pkg/ (stored 0%)
  adding: example_pkg/a/ (stored 0%)
  adding: example_pkg/a/__init__.py (stored 0%)
draft $ rm -r example_pkg                                                                                                                                                      
draft $ env PYTHONPATH=example_pkg.zip python3 -c "import example_pkg.a"
draft $
```

I suspect the issue is that the wheels that pip is producing are not creating the `example_pkg` directory in the zip file.

Confirmed:

```
sample-namespace-packages master $ cd native/pkg_a                                                                                                                             
pkg_a master $ pip wheel .                                                                                                                                                     
Processing /Users/jaraco/code/public/pypa/sample-namespace-packages/native/pkg_a
Building wheels for collected packages: example-pkg-a
  Building wheel for example-pkg-a (setup.py) ... done
  Stored in directory: /Users/jaraco/code/public/pypa/sample-namespace-packages/native/pkg_a
Successfully built example-pkg-a
pkg_a master $ cd ..                                                                                                                                                           
native master $ env PYTHONPATH=pkg_a/example_pkg_a-1-py3-none-any.whl python3 -c "import example_pkg.a"                                                                        
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'example_pkg'
native master $ mkdir example_pkg                                                                                                                                              
native master $ zip pkg_a/example_pkg_a-1-py3-none-any.whl example_pkg                                                                                                         
  adding: example_pkg/ (stored 0%)
native master $ rmdir example_pkg                                                                                                                                              
native master $ env PYTHONPATH=pkg_a/example_pkg_a-1-py3-none-any.whl python3 -c "import example_pkg.a" && echo "done"                                                         
done
```

Simply adding `example_pkg/` to the zipfile allowed Python to recognize that wheel as having that directory and thus having that namespace package.

The way I see it, there are two ways to think about this issue:

1. If it's valid for zip files to contain files in directories but not contain entries for those directories, then Python (and probably other zip implementations) need to add support for detecting directories implied by their contents.
2. If it's not valid for zip files to contain files in directories but not explicitly present entries for such directories, then it's a bug that the wheel project doesn't create such entries.

I encountered this concern when implementing [zipp](https://pypi.org/project/zipp), where my experiments led me to [assume directory entries were present](https://github.com/jaraco/zipp/blob/b06993c3b000bb3a45b2ebe57141370dd588a378/zipp.py#L79), in part because I experimented and found that both zip tools and Python's zipfile module would both create these entries by default when constructing a zipfile from a file system.

The [Wikipedia entry](https://en.wikipedia.org/wiki/Zip_(file_format)) on this issue doesn't address the issue at all, but [this comment](https://stackoverflow.com/questions/37292799/zipfile-createfromdirectory-does-not-include-directory-entries#comment62112242_37293012) indicates that the 'directory' entry is a convention and an unreliable one at that (sometimes with forward slashes and sometimes with backslashes), although it does seem that the trailing `/` is the most common convention.

My pragmatic side tells me that the easiest and most practical way to address this issue is to ensure that the `wheel` package includes directory entries. That will address the issue going forward for new wheels built with that version of wheel. Other avenues we might explore separately:

- update the wheel spec to require that zip files follow this convention (at least for namespace packages).
- update Python's import machinery to detect implied directories (adds support for older wheels).

**Comment by jaraco** [comment] 2019-04-26 17:51
@pfmoore Do you have any opinion on updating the wheel spec to require that zip files have directory entries?

@brettcannon What's your take on the zipimport functionality - should it detect implied directories for detecting namespace packages? If so, I can start by filing the bpo ticket.

**Comment by cas--** [comment] 2019-04-26 19:15
Thanks for quick reply, adding the missing directories with zip does workaround the issue! Really had me scratching my head, never would have guessed that :open_mouth: 

I think this might be one of the last pieces of the puzzle to having entrypoint plugins as wheels working in Deluge and I will update with my findings.

**Comment by jaraco** [comment] 2019-04-26 19:45
I've confirmed that the [patch here](https://github.com/pypa/wheel/issues/287#issuecomment-487156927) creates wheels that build with the requisite directories, and namespace packages work. All that's needed now is a unit test to capture the requisite behavior and to tests made to fail with the patch.

**Comment by brettcannon** [comment] 2019-04-26 21:30
@jaraco I'm not sure what you mean by "implied directories for detecting namespace packages"? If it's in relation to "If it's valid for zip files to contain files in directories but not contain entries for those directories", then I'm still not sure what you mean. :) Are you asking if zip files that lack a specific directory entry in their TOC for a directory but have files in the unlisted directory? In that situation I would ask what the zip spec says.

**Comment by pfmoore** [comment] 2019-04-26 21:48
@jaraco It sounds to me like the motivating use case for wheel adding the directory entries is to put wheels on `sys.path`. Given that this is explicitly documented in the wheel PEP as a non-goal of the format, I don't think there's any justification for a spec change (or a change to the wheel project - but that one is not my call) here.

If there's a need for the "importable zipfile" features provided by eggs (beyond the simple fact that zipimport allows you to import from *any* zipfile) then it should be made into a proper proposal in its own right. That proposal could reasonably argue that the proposed format could made compatible with wheels - but personally I remain unconvinced that conflating a distribution file format and a runtime file format is a good idea.

If my understanding of what's behind this is wrong, then please clarify. I've not been following this thread at all.

**Comment by jaraco** [comment] 2019-04-27 02:36
> Are you asking if zip files that lack a specific directory entry in their TOC for a directory but have files in the unlisted directory?

I'm asking if zipfile importer should support namespace packages found in such implied directories, yes.

> In that situation I would ask what the zip spec says.

In my research, the zip "spec" is silent on that concern. It seems to be unspecified.

> the motivating use case for wheel adding the directory entries is to put wheels on `sys.path`

Yes, essentially a duplicate of #244. Pip has dropped support for eggs. Eggs rely on deprecated behavior in setuptools. Eggs aren't mentioned at all in PEP 517/518. This is just another use-case that exemplifies why users need a container format for importable behavior (plugins).

> I don't think there's any justification for a spec change

Without such a spec change, wheels will be allowed to be actively hostile to importability... and the `wheel` project would be justified in holding to that hostility. Ambiguity in a standard leads to consternation and confusion. The zip format is itself also hostile in that sense, given that it doesn't seem to declare a standard for designating containers (directories/folders). The wheel format _could_ collapse this uncertainty if it chose to do so.

Nevertheless, #244 is a broader, superseding perspective on this issue, so I'm going to close accordingly.

**Closed by jaraco** 2019-04-27 02:36 UTC

**Comment by pfmoore** [comment] 2019-04-27 09:43
Just to clarify on one point - I think that zipimport should support implicit namespace packages, and given that the zip spec is silent on the matter of entries for directories, and we know that some zipfiles in the wild don't include them, I'd say that a bug report against zipimport would be reasonable. That obviously only helps for future Python versions, so maybe the container format spec being discussed in #244 should mandate that directory entries are created for implicit namespace packages as well, to provide backward compatibility. (One potential point that needs clarifying here is that it's not entirely obvious how to create a "directory entry" item in a zipfile using the stdlib zipfile module - I assume you create an entry with a name ending in `/`, but I don't think it's clear from the docs that this is the correct or supported way of doing so).

**Comment by jaraco** [comment] 2019-04-27 13:11
Thanks Paul. I’ve filed the zipimport issue as [bpo-36740](https://bugs.python.org/issue36740).

**Comment by cas--** [comment] 2019-04-30 20:25
@jaraco There is still the problem I am facing with pkgutil not importing when an existing namespace on sys.path. Should I open a new issue or are you able to determine the issue for that too here?

As a reminder:

```
cd pkgutil
mkdir example_pkg
cp pkg_a/example_pkg/__init__.py example_pkg
env PYTHONPATH=pkg_a/dist/example_pkg_a-1-py3-none-any.whl python3
>>> import example_pkg.a
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'example_pkg.a'
>>> 
```

And I have encountered an alternative method to to raise this error. I originally found it testing with my application, where if I import the package namespace before adding the plugin to the path I am unable to import the plugin afterwards:

```
cd pkgutil
mkdir example_pkg
cp pkg_a/example_pkg/__init__.py example_pkg
python3
>>> import example_pkg
>>> import sys; sys.path.insert(0, 'pkg_a/dist/example_pkg_a-1-py3.7.egg')
>>> import example_pkg.a
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'example_pkg.a'
```

This however works:
```
>>> import sys; sys.path.insert(0, 'pkg_a/dist/example_pkg_a-1-py3.7.egg')
>>> import example_pkg
>>> import example_pkg.a
```

I'm a bit puzzled by this and would really appreciate some help working around it!

**Comment by jaraco** [comment] 2019-05-04 14:14
> There is still the problem I am facing with pkgutil not importing when an existing namespace on sys.path.

This sounds like a separate issue, maybe with pkgutil or maybe with zipimport. Let's explore further.

```
pkgutil master $ mkdir example_pkg                                                                                                                                             
pkgutil master $ cp pkg_a/example_pkg/__init__.py example_pkg                                                                                                                  
pkgutil master $ env PYTHONPATH=pkg_a/dist/example_pkg_a-1-py3.7.egg python3                                                                                                   
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 16:52:21) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import example_pkg.a
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'example_pkg.a'
>>> import example_pkg
>>> example_pkg.__spec__
ModuleSpec(name='example_pkg', loader=<_frozen_importlib_external.SourceFileLoader object at 0x10b173438>, origin='/Users/jaraco/code/public/pypa/sample-namespace-packages/pkgutil/example_pkg/__init__.py', submodule_search_locations=['/Users/jaraco/code/public/pypa/sample-namespace-packages/pkgutil/example_pkg'])
>>> import sys
>>> sys.path
['', '/Users/jaraco/code/public/pypa/sample-namespace-packages/pkgutil/pkg_a/dist/example_pkg_a-1-py3.7.egg', '/Library/Frameworks/Python.framework/Versions/3.7/lib/python37.zip', '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7', '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload', '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages', '/Users/jaraco/code/public/xonsh']
>>> example_pkg.__path__
['/Users/jaraco/code/public/pypa/sample-namespace-packages/pkgutil/example_pkg', './example_pkg']
```

I think what's happening is because '.' is first on the path, and because `./example_pkg/__init__.py` exists, the `SourceFileLoader` is used, and somehow that prevents the zip file (egg) from being considered, even though it's in the path. Somehow, the call to `pkg_util.extend_path()` isn't having the intended effect.

Reading [the docs for extend_path](https://docs.python.org/3/library/pkgutil.html#pkgutil.extend_path), the description doesn't indicate why mixed filesystem and zipfile imports wouldn't work, which probably isn't a surprised given the [known limited test coverage of that function](https://bugs.python.org/issue14817).

Using `pdb`, I was able to trace the pkgutil code and it does appear that the zipimporter is somehow not finding any packages under example_pkg:

```
$ env PYTHONPATH=pkg_a/dist/example_pkg_a-1-py3.7.egg python3                                                                                                   
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 16:52:21) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pdb
>>> pdb.run('import example_pkg.a')
> <string>(1)<module>()
(Pdb) b pkgutil.py:556
Breakpoint 1 at /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pkgutil.py:556
(Pdb) c
> /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pkgutil.py(556)extend_path()
-> for dir in search_path:
(Pdb) search_path
['', '/Users/jaraco/code/public/pypa/sample-namespace-packages/pkgutil/pkg_a/dist/example_pkg_a-1-py3.7.egg', '/Library/Frameworks/Python.framework/Versions/3.7/lib/python37.zip', '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7', '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload', '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages', '/Users/jaraco/code/public/xonsh']
(Pdb) c
> /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pkgutil.py(556)extend_path()
-> for dir in search_path:
(Pdb) n
> /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pkgutil.py(557)extend_path()
-> if not isinstance(dir, str):
(Pdb) dir
'/Users/jaraco/code/public/pypa/sample-namespace-packages/pkgutil/pkg_a/dist/example_pkg_a-1-py3.7.egg'
(Pdb) n
> /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pkgutil.py(560)extend_path()
-> finder = get_importer(dir)
(Pdb) n
> /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pkgutil.py(561)extend_path()
-> if finder is not None:
(Pdb) finder
<zipimporter object "/Users/jaraco/code/public/pypa/sample-namespace-packages/pkgutil/pkg_a/dist/example_pkg_a-1-py3.7.egg">
(Pdb) n
> /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pkgutil.py(562)extend_path()
-> portions = []
(Pdb) n
> /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pkgutil.py(563)extend_path()
-> if hasattr(finder, 'find_spec'):
(Pdb) n
> /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pkgutil.py(568)extend_path()
-> elif hasattr(finder, 'find_loader'):
(Pdb) n
> /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pkgutil.py(569)extend_path()
-> _, portions = finder.find_loader(final_name)
(Pdb) n
> /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pkgutil.py(571)extend_path()
-> for portion in portions:
(Pdb) portions
[]
(Pdb) final_name
'example_pkg'
(Pdb) finder.find_loader('example_pkg')
(<zipimporter object "/Users/jaraco/code/public/pypa/sample-namespace-packages/pkgutil/pkg_a/dist/example_pkg_a-1-py3.7.egg">, [])
```

I can't pdb into zipimport because of how it's imported, but I suspect `zipimport._get_module_info` is returning `None`.

**Comment by jaraco** [comment] 2019-05-04 14:42
Aha - I've been testing against Python 3.7, but it's only in Python 3.8 that [zipimport gets ported to pure Python](https://bugs.python.org/issue25711).

**Comment by jaraco** [comment] 2019-05-04 14:56
Python 3.8 has the same behavior and I've confirmed that `zipimport._get_module_info` is returning `True` for `_get_module_info`.

**Comment by jaraco** [comment] 2019-05-04 15:16
I think what this boils down to is `pkgutil`-style namespace packages aren't supported in zip files.

```
$ env PYTHONPATH=pkg_a/dist/example_pkg_a-1-py3.7.egg:pkg_b/dist/example_pkg_b-1-py3.7.egg python3                                                              
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 16:52:21) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import example_pkg.a
>>> import example_pkg.b
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'example_pkg.b'
```

**Comment by jaraco** [comment] 2019-05-04 15:18
A limitation which is actually (though subtly) [documented here](https://packaging.python.org/guides/packaging-namespace-packages/#creating-a-namespace-package):

> pkg_resources-style namespace packages method is recommended ... if your package needs to be zip-safe.

**Comment by jaraco** [comment] 2019-05-04 15:25
And that limitation is unlikely to be lifted, since PEP 420 namespace packages are preferred for packages that can rely on Python 3.5 or later.

**Comment by cas--** [comment] 2019-05-06 09:27
This is a bit of a mess then if native namespace in zip-safe packages have been sidelined because now there is no migration path with this use-case on Python 3... In order to future-proof the code and drop pkg_resources dependency, I'll have to remove namespace support from all the plugins.

Is this something that should be considered in the discussion in #244?

**Comment by jaraco** [comment] 2019-05-06 13:57
@cas-- I agree - it's a real problem, but somewhat different than the originally-posted issue and also distinct from #244. I recommend we open a new ticket to capture this distilled issue, but before we do - can you rely on the `pkg_resources` technique until Python 3.5+ is required, at which point you could switch to native namespace packages? I recognize "switch" is an abrupt and harsh transition because packages in a namespace can't share the technique. What I want to figure out is - should we focus on getting pkg_resources to have nicer compatibility with native namespace packages (may or may not be possible) or should we focus on improved pkgutil compatibility for zip importers (likely not possible due to immutability of pkgutil code in older Python versions)?

**Comment by cas--** [comment] 2019-05-08 17:25
The current scenario is that the existing Deluge 1.3 Py2-only plugins don't use a pkg_resources namespace but in development code they were converted to pkg_resources namespace to avoid module name collision. It's not released yet so I have the opportunity to switch to native namespace or could use a naming prefix instead of namespace but I feel the latter is quite hacky and annoying to code around in the plugin manager.

In my initial testing I could not get native namespace eggs to work but just realised it has the same zip implicit directory issue affects the eggs too. Should an issue be raised with setuptools for this?

With regards to the pkgutil namespace issue, I guess pkg_resources playing nice with native namespace would help legacy code.
