### ISSUE TITLE
pypa/build on Linux - extension / binary modules in purelib

### ISSUE THREAD

**Issue by tcuongd** [pypa/packaging-problems#542] opened 2021-09-03 17:27 UTC
Hello! I'm building a package on Linux with extension modules, using `setuptools` + `wheel`, and `pypa/build` to run the build command. I've added a custom distribution class to force platform-specific wheels:

```python
class BinaryDistribution(Distribution):
    """Distribution which always forces a binary package with platform name"""
    def has_ext_modules(self):
        return True

    def is_pure(self):
        return False

setup(..., distclass=BinaryDistribution)
```

This successfully generates a Linux-specific wheel. Now I want to "repair" the wheel in order to publish it to PyPi. I'm using `pypa/auditwheel` for this, but it gives this error:

```
RuntimeError: Invalid binary wheel, found the following shared library/libraries in purelib folder:
  	prophet_model.bin
  	diagnose
  	print
  	stanc
  	stansummary
  	diagnose.o
  	print.o
  	stansummary.o
  	bernoulli
  	main.o
The wheel has to be platlib compliant in order to be repaired by auditwheel.
```

I had initially thought it could be an issue with auditwheel (posted a question here: https://github.com/pypa/auditwheel/issues/333#issue-982011357) but I noticed that auditwheel is simple checking the metadata of the wheel here. I'm wondering if there's actually an issue in the wheel creation that's causing the extension modules to land in `purelib`. Would really appreciate any tips / where to start looking to solve this!

**Comment by layday** [comment] 2021-09-03 22:14
The problem is that you're declaring the root to be "platlib" but the stuff you're packaging setuptools/wheel believes to be _pure_, so it places them in `xyz.data/purelib` in the wheel. Then when auditwheel inspects the wheel it finds them there and errors out.  I assume this is for facebook/prophet - you don't need a custom `distclass` here - you just need to subclass `build_ext` instead of `build_py`.

**Comment by layday** [comment] 2021-11-15 09:39
Looks like you got it sorted so I'll go ahead and close this one.

**Closed by layday** 2021-11-15 09:39 UTC
