### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by Microstudio-office** [pypa/packaging-problems#403] opened 2020-10-06 13:41 UTC
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

Windows10

2. What is your Python version?

Python 3.8.6

3. What version of pip do you have?

pip 20.2.3

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

cmd：C:\Users\UPC\Desktop\packaging_tutorial>setup.py sdist bdist_wheel
Traceback (most recent call last):
  File "C:\Users\UPC\Desktop\packaging_tutorial\setup.py", line 4, in <module>
    ext_modules = cythonize("a.py"))
  File "C:\Users\UPC\AppData\Local\Programs\Python\Python38\lib\site-packages\Cython\Build\Dependencies.py", line 965, in cythonize
    module_list, module_metadata = create_extension_list(
  File "C:\Users\UPC\AppData\Local\Programs\Python\Python38\lib\site-packages\Cython\Build\Dependencies.py", line 815, in create_extension_list
    for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
  File "C:\Users\UPC\AppData\Local\Programs\Python\Python38\lib\site-packages\Cython\Build\Dependencies.py", line 114, in nonempty
    raise ValueError(error_msg)
ValueError: 'a.py' doesn't match any files

5. Could you describe your issue in as much detail as possible?

url：https://packaging.python.org/tutorials/packaging-projects/

**Comment by merwok** [comment] 2020-10-06 18:41
Can you show the contents of your `setup.py`?

**Comment by merwok** [comment] 2020-10-06 18:45
Hello!  It seems that you’re not packaging a basic project as in the tutorial, but using Cython.
I don’t use it, but from its docs it seems that the `cythonize` function works with `pyx` files, not `py`.  Or maybe the issue is that there isn’t a file named `a.py` in your directory!

Can you share:
- the Cython docs you are using
- your setup.py script
- how your code is laid out (like a screeshot of your directory tree)

**Comment by layday** [comment] 2021-03-28 12:28
I'll close this now but feel free to comment below if the problem persists.

**Closed by layday** 2021-03-28 12:28 UTC
